### ISSUE TITLE
Lesson 9 Re-Review

### ISSUE THREAD

**Issue by kozel-stas** [ilyaQA25/QA-25lya_Prez_#17]
Остался последний нюанс)
Открой запись последнего занятия на 9.25 примерно. Я объяснял, что имею ввиду об месте где вызываются проверки.
Те в методе Main это неправильное место - правильное место в документе или в регистре.

**Comment by ilyaQA25** [comment]
Эксепшены добавил в класс Registr, в метод saveDoc()
создал абстрактный класс DocumentInvalidException, от которого наследуются другие эксепшены
